spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/apisecurityapp
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  # Set the root logger level to INFO
logging:
  level:
    root: INFO

